[package]
name = "fix"
version = "0.1.0"
authors = ["Aleksander Fular <ntszar@gmail.com>", "Piotr Mis <piotrekmis@gmail.com>"]

[dependencies]
chrono = "*"
log = "*"
native-tls = "0.1"

[dev-dependencies]
quickcheck = "*"