[package]
name = "profix_derive"
version = "0.1.0"
authors = ["Aleksander Fular <ntszar@gmail.com>", "Piotr Mis <piotrekmis@gmail.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true
